Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-reload"]

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 2
    v.gui = true
  end

  config.vm.define "workstation1" do |workstation1|
    workstation1.vm.guest = :windows
    workstation1.vm.communicator = "winrm"
    workstation1.vm.boot_timeout = 600
    workstation1.vm.graceful_halt_timeout = 600
    workstation1.winrm.retry_limit = 200
    workstation1.winrm.retry_delay = 10
    workstation1.winrm.max_tries = 20
    workstation1.winrm.transport = :plaintext
    workstation1.winrm.basic_auth_only = true
    workstation1.vm.box = "StefanScherer/windows_10"

    workstation1.name = "cuckoo1"
    workstation1.vm.network "private_network", ip: "192.168.56.101", gateway: "192.168.56.1", dns: "192.168.56.1", name: "vboxnet0"
    workstation1.vm.network :forwarded_port, guest: 5985, host: 35985, id: "winrm"
    workstation1.vm.network :forwarded_port, guest: 3389, host: 33389, id: "msrdp"
    workstation1.vm.hostname = "labworkstation1"
    workstation1.vm.provision "shell", privileged: false, inline: <<-SHELL
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name AutoAdminLogon -Value 1
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name DefaultUserName -Value "vagrant"
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name DefaultPassword -Value "vagrant"
      Remove-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name AutoAdminLogonCount -Confirm -ErrorAction SilentlyContinue
      reg add HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v EnableLUA /d 0 /t REG_DWORD /f /reg:64
    SHELL
    workstation1.vm.provision "reload"
  end

end